# Generated by Django 4.0.6 on 2022-12-06 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0020_leavereportstaff_leave_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollReportStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payroll_date', models.DateField(null=True)),
                ('payroll_money', models.IntegerField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management_app.staffs')),
            ],
        ),
    ]
