# Generated by Django 4.1.3 on 2022-12-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0021_group_site_payrollreportstaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayrollReportStaff',
        ),
    ]
