# Generated by Django 4.1.3 on 2022-12-19 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0022_delete_payrollreportstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management_app.group'),
        ),
    ]
