# Generated by Django 4.1.3 on 2022-12-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0027_customuser_group_id_customuser_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='site_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management_app.site'),
        ),
        migrations.DeleteModel(
            name='Staffs3',
        ),
    ]
