# Generated by Django 4.1.3 on 2022-12-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0028_staffs_site_id_delete_staffs3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereportstaff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
