# Generated by Django 4.0.6 on 2022-12-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0021_payrollreportstaff'),
        ('employee_management_app', '0029_alter_attendancereportstaff_id'),
    ]

    operations = [
    ]
